[mypy]
mypy_path = airdrops/src
explicit_package_bases = True
warn_return_any = True
warn_unused_configs = True
exclude = airdrops/venv/.*|venv/.*|\.venv/.*|tests/.*
packages = airdrops

[mypy-apscheduler.*]
ignore_missing_imports = True

[mypy-docutils.*]
ignore_missing_imports = True

[mypy-airdrops.shared.recovery_manager]
ignore_missing_imports = True

[mypy-airdrops.shared.state_manager]
ignore_missing_imports = True

[mypy-airdrops.shared.gas_manager]
ignore_missing_imports = True

[mypy-airdrops.shared.protocol_manager]
ignore_missing_imports = True

[mypy-airdrops.shared.circuit_breaker]
ignore_missing_imports = True