#!/usr/bin/env python3
"""Generate testnet wallets for cryptofarm airdrops testing."""

import json
from eth_account import Account
import secrets
from pathlib import Path

def generate_wallet():
    """Generate a new Ethereum wallet with private key and address."""
    # Generate random private key
    priv = secrets.token_hex(32)
    private_key = "0x" + priv
    
    # Create account from private key
    acct = Account.from_key(private_key)
    
    return {
        "address": acct.address,
        "private_key": private_key
    }

def main():
    """Generate wallets for all required testnets."""
    # Define the networks we need wallets for
    networks = [
        "SEPOLIA",
        "ZKSYNC_SEPOLIA",
        "SCROLL_SEPOLIA",
        "ARBITRUM_SEPOLIA",
        "HOLESKY"
    ]
    
    wallets = {}
    env_vars = []
    
    print("🔑 Generating testnet wallets...")
    print("=" * 60)
    
    for network in networks:
        wallet = generate_wallet()
        wallets[network] = wallet
        
        print(f"\n{network}:")
        print(f"  Address: {wallet['address']}")
        print(f"  Private Key: {wallet['private_key'][:10]}...{wallet['private_key'][-6:]}")
        
        # Prepare environment variable
        env_var = f"TESTNET_PRIVATE_KEY_{network}={wallet['private_key']}"
        env_vars.append(env_var)
    
    # Save wallets to JSON file (for backup)
    output_dir = Path(__file__).parent.parent / "testnet_wallets"
    output_dir.mkdir(exist_ok=True)
    
    wallets_file = output_dir / "wallets.json"
    with open(wallets_file, "w") as f:
        json.dump(wallets, f, indent=2)
    
    # Create .env.testnet file
    env_file = Path(__file__).parent.parent.parent / ".env.testnet"
    with open(env_file, "w") as f:
        f.write("# Testnet Private Keys for Mock Validation\n")
        f.write("# Generated by generate_testnet_wallets.py\n")
        f.write("# IMPORTANT: Never commit this file to version control\n\n")
        
        for env_var in env_vars:
            f.write(env_var + "\n")
    
    print("\n" + "=" * 60)
    print("✅ Wallets generated successfully!")
    print(f"📄 Wallet details saved to: {wallets_file}")
    print(f"📄 Environment variables saved to: {env_file}")
    print("\n⚠️  IMPORTANT: Keep these private keys secure!")
    print("    Never share them or commit them to version control.")
    
    # Print funding instructions
    print("\n" + "=" * 60)
    print("💰 Next Steps - Fund Your Wallets:")
    print("\n1. Ethereum Sepolia:")
    print("   - https://faucets.chain.link/sepolia")
    print("   - https://www.alchemy.com/faucets/ethereum-sepolia")
    print("   - https://sepolia-faucet.pk910.de/")
    
    print("\n2. zkSync Era Sepolia:")
    print("   - https://faucets.chain.link/zksync-sepolia")
    print("   - https://www.alchemy.com/faucets/zksync-sepolia")
    
    print("\n3. Scroll Sepolia:")
    print("   - https://faucets.chain.link/scroll-sepolia-testnet")
    print("   - https://bwarelabs.com/faucets/scroll-testnet")
    
    print("\n4. Arbitrum Sepolia:")
    print("   - https://faucets.chain.link/arbitrum-sepolia")
    print("   - https://www.alchemy.com/faucets/arbitrum-sepolia")
    
    print("\n5. Ethereum Holesky:")
    print("   - https://faucets.chain.link/holesky")
    print("   - https://www.alchemy.com/faucets/ethereum-holesky")
    
    print("\n📝 Note: Most faucets require:")
    print("   - Mainnet balance (0.001 ETH) for anti-bot protection")
    print("   - Social media verification (Twitter/Discord)")
    print("   - Rate limiting (once per 24-72 hours)")

if __name__ == "__main__":
    main()